const {Sequelize,DataTypes}=require('sequelize')
const config=require('../Config/Config')
const sequelize=new Sequelize(config.development)
sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch((err) => {
    console.error('Unable to connect to the database:', err);
  });
  const KakinadaRural=sequelize.define('KakinadaRural',{
    S_no:{
      type:DataTypes.INTEGER,
      primaryKey:true
    },
    Voter_S_no:{
      type:DataTypes.INTEGER,
      allowNull:false
    },
    Epic:{
      type:DataTypes.STRING,
      allowNull:true
    },
    Name:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Father_Name:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Surname:{
        type:DataTypes.STRING,
        allowNull:true
      },
      House_Number:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Age:{
        type:DataTypes.INTEGER,
        allowNull:true
      },
      Gender:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Area:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Constituency:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Mandal:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Village:{
        type:DataTypes.STRING,
        allowNull:true
      },     
      Pincode:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Polling_Station:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Booth:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Mp:{
        type:DataTypes.STRING,
        allowNull:true
      },
      District:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Age_grp:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Wards:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Mobile:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Remarks:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Problems:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Survey:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Availability:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Location:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Caste:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Color:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Observation:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Surveyer:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Surveyed_on:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Created_at:{
        type:DataTypes.DATE,
        allowNull:true
      },
      Geo:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Latitude:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Longitude:{
        type:DataTypes.STRING,
        allowNull:true
      },
      Survey_id:{
        type:DataTypes.STRING,
        allowNull:true
      },
    survey_date:{
        type:DataTypes.DATE,
        allowNull:true
    }
  },{
    timestamps:false,
    tableName:"kakinada_rural_"
  })

  module.exports = { KakinadaRural, sequelize };